### ISSUE TITLE
It freezes after a few hours of operation

### ISSUE THREAD

**Issue by techcom2** [alexCajas/EmbeddedMqttBroker#8] opened 2022-12-28 18:13 UTC
Example simpleMqttBroker.ino sketch
Two clients broadcast every 20 seconds, hangs after a few hours of work.

17:17:30.581 -> publishing: 1234/stan
17:17:30.581 -> enviando publish
17:17:39.364 -> sending ping response packet
17:17:45.727 -> publishing: 1234/stan
17:17:45.727 -> enviando publish
17:18:01.748 -> deleting client
17:18:04.958 -> deleting client
17:22:51.416 -> new client
17:22:51.416 -> 2
17:22:51.416 -> #
17:22:59.981 -> new client
17:22:59.981 -> 3
17:23:45.044 -> new client
17:23:45.044 -> 4
17:23:51.613 -> sending ping response packet
17:24:30.122 -> new client
17:24:30.122 -> 5
17:24:51.605 -> sending ping response packet
17:25:51.636 -> sending ping response packet
17:26:52.606 -> deleting client

**Comment by alexCajas** [comment] 2023-01-10 22:31
Hi! @techcom2  can you get some more information? like: some memory issue, clients still connected after broker stop to print ?? I trying to reproduce the issue but I can't now. The clients are desktop software or some esp device?

**Comment by techcom2** [comment] 2023-01-11 10:07
Hello,
2 customers
-0 is PC MQTT Explorer (receiving only)
-1 is ESP8266 sending packet every 10s
I added in the main loop:
`unsigned long currentTime = millis();

  if (currentTime - previousTime >= eventInterval) {
    Serial.println(ESP.getFreeHeap()); 
    previousTime = currentTime;
  }`
eventInterval = 10s.
![start](https://user-images.githubusercontent.com/121573834/211777550-19b923e8-5f33-4a58-ac87-d7054ed6ef5c.jpg)
![stop](https://user-images.githubusercontent.com/121573834/211777581-7e69993c-77c1-4480-a6e9-a37a831d51f5.jpg)

**Comment by alexCajas** [comment] 2023-02-13 20:36
@techcom2 hi!, there is available new version of this library, can you test the issue again please? in this case, enable core debug level to verbose, and let me see the outputs, I tested the broker for some days with no error:
2 costommers:
- Esp32 like broker and client subscribed to "#"
- One esp8266 publising severals topics with no payload each 10 seconds.

**Comment by sramrajkar** [comment] 2023-04-25 22:14
I can confirm that current master version of this lib is leaking memory as shows in the above picture. I have 5 clients each reporting every 1 sec. I can confirm by using them or just one PC client that on every message being published the broker leaks memory.
I can also confirm the issue is not in the function where the broker finds all subscriptions and forwards them to the clients.

**Comment by cavefire** [comment] 2023-11-06 11:08
I can also confirm that. In my tests 15 clients connect, each sending one message per second.
After about 2000 messages it stops responding. 

Adding a `free(publishMessage)` after calling `notifyPublishReceivedCallback` in https://github.com/alexCajas/EmbeddedMqttBroker/blob/70c596b8f756a3d6fec768feaf59c415a6008f30/src/MqttClient/MqttClient.cpp#L76 seems to make a difference. Now I am up to 4000 messages in. Did anyone else find another memory leak?

**Comment by alexCajas** [comment] 2023-11-06 19:47
ok thanks for you support guys. @cavefire when you send 4000 messages does the broker freeze or work fine?

**Comment by alexCajas** [comment] 2023-12-17 17:09
fixed in v1.0.7-qos0.

**Closed as completed by alexCajas** 2023-12-17 17:09 UTC
